#!/usr/bin/env python3
"""
CAMRIE Mode 2 — Worker Manager

Deploy, monitor, and teardown your Mode 2 CAMRIE computing unit on AWS.
Includes a GUI (tkinter) for non-expert users.

Usage:
    python worker/manage.py              — Opens GUI
    python worker/manage.py deploy       — Deploy the worker stack
    python worker/manage.py status       — Check worker health + running tasks
    python worker/manage.py logs         — Tail recent computation logs
    python worker/manage.py costs        — Show estimated costs
    python worker/manage.py teardown     — Delete the stack (stop all costs)

Requirements:
    pip install -r worker/requirements.txt
    AWS CLI configured (aws configure --profile <your-profile>)

CloudMR credentials come from --email/--password, the CLOUDMR_EMAIL /
CLOUDMR_PASSWORD environment variables, or an interactive (hidden) prompt.
See worker/README.md.
"""

import argparse
import json
import os
import sys
import time
import uuid
from datetime import datetime, timedelta
from pathlib import Path

try:
    import boto3
    import requests
except ImportError:
    print("Missing dependencies. Run: pip install boto3 requests")
    sys.exit(1)


# ═══════════════════════════════════════════════════════════════
# Configuration
# ═══════════════════════════════════════════════════════════════
APP_NAME = "CAMRIE"
STACK_NAME = "camrie-worker-mode2"
TEMPLATE_PATH = Path(__file__).parent / "deploy" / "template.yaml"
CONFIG_DIR = Path.home() / ".camrie"
CONFIG_PATH = CONFIG_DIR / "config.toml"
BRAIN_API_URL = "https://brain.aws.cloudmrhub.com/Prod"
ECR_IMAGE = os.environ.get("CAMRIE_WORKER_IMAGE", "public.ecr.aws/r2m7t0q6/cloudmrhub/camrie-fargate:latest")
DEFAULT_REGION = "us-east-1"


def get_aws_profiles():
    """List available AWS CLI profiles."""
    profiles = set()
    for path in [Path.home() / ".aws" / "config", Path.home() / ".aws" / "credentials"]:
        if path.exists():
            with open(path) as f:
                for line in f:
                    line = line.strip()
                    if line.startswith("[profile "):
                        profiles.add(line[9:].rstrip("]"))
                    elif line.startswith("[") and not line.startswith("[default"):
                        profiles.add(line.strip("[]"))
    profiles.add("default")
    return sorted(profiles)


def load_config():
    """Load saved config from ~/.camrie/config.toml."""
    config = {}
    if CONFIG_PATH.exists():
        try:
            with open(CONFIG_PATH, encoding="utf-8", errors="replace") as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith("#") and "=" in line:
                        key, val = line.split("=", 1)
                        config[key.strip()] = val.strip().strip('"').strip("'")
        except Exception:
            pass
    return config


def save_config(**kwargs):
    """Save config to ~/.camrie/config.toml."""
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    lines = [
        "# CAMRIE Mode 2 — saved configuration",
        "# Auto-generated by manage.py deploy",
        f"# Location: {CONFIG_PATH}",
        "",
    ]
    for key, val in kwargs.items():
        if val:
            lines.append(f'{key} = "{val}"')
    lines.append("")
    CONFIG_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"  Config saved to {CONFIG_PATH}")


# ═══════════════════════════════════════════════════════════════
# Helpers
# ═══════════════════════════════════════════════════════════════
def color(text, c):
    colors = {"green": "\033[92m", "red": "\033[91m", "yellow": "\033[93m",
              "blue": "\033[94m", "bold": "\033[1m", "end": "\033[0m"}
    return f"{colors.get(c, '')}{text}{colors['end']}"


def get_session(profile=None, region=None):
    return boto3.Session(profile_name=profile, region_name=region or DEFAULT_REGION)


def get_stack_outputs(session, stack_name=STACK_NAME):
    cf = session.client("cloudformation")
    try:
        resp = cf.describe_stacks(StackName=stack_name)
        stack = resp["Stacks"][0]
        outputs = {o["OutputKey"]: o["OutputValue"] for o in stack.get("Outputs", [])}
        return stack["StackStatus"], outputs
    except Exception:
        return None, {}


def empty_stack_buckets(session, stack_name=STACK_NAME):
    """Empty the stack's S3 buckets. CloudFormation cannot delete a
    non-empty bucket, so teardown would otherwise fail with DELETE_FAILED."""
    _, outputs = get_stack_outputs(session, stack_name)
    s3 = session.resource("s3")
    for key in ("ResultsBucketName", "EventsBucketName"):
        name = outputs.get(key)
        if not name:
            continue
        try:
            bucket = s3.Bucket(name)
            bucket.object_versions.delete()
            bucket.objects.all().delete()
            print(f"  Emptied bucket {name}")
        except Exception as e:
            print(color(f"  Could not empty {name}: {e}", "yellow"))


def print_stack_failures(cf, stack_name=STACK_NAME):
    """Print the resources that failed, since the waiter error alone says nothing."""
    try:
        events = cf.describe_stack_events(StackName=stack_name)["StackEvents"]
        for ev in events[:40]:
            if ev["ResourceStatus"].endswith("FAILED"):
                print(color(f"    {ev['LogicalResourceId']}: "
                            f"{ev.get('ResourceStatusReason', '')}", "red"))
    except Exception:
        pass


def brain_login(email, password):
    resp = requests.post(f"{BRAIN_API_URL}/api/auth/login",
                         json={"email": email, "password": password})
    data = resp.json()
    token = data.get("id_token") or data.get("idToken") or data.get("access_token")
    if not token:
        print(color(f"Login failed: {data.get('message', 'Unknown error')}", "red"))
        sys.exit(1)
    return data


def prompt(text, default=None, secret=False):
    suffix = f" [{default}]" if default else ""
    if secret:
        import getpass
        val = getpass.getpass(f"{text}{suffix}: ")
    else:
        val = input(f"{text}{suffix}: ")
    return val.strip() or default


# ═══════════════════════════════════════════════════════════════
# Commands
# ═══════════════════════════════════════════════════════════════

def cmd_deploy(args):
    """Deploy the Mode 2 worker stack to AWS."""
    print(color("\n╔═══════════════════════════════════════════════╗", "blue"))
    print(color("║  CAMRIE Mode 2 — Deploy Worker                  ║", "blue"))
    print(color("╚═══════════════════════════════════════════════╝\n", "blue"))

    cfg = load_config()
    register = not getattr(args, "no_register", False)
    profile = args.profile or prompt("AWS CLI profile", cfg.get("profile", "default"))
    region = args.region or prompt("AWS region", cfg.get("region", DEFAULT_REGION))
    email = password = token = None
    if register:
        email = (args.email or os.environ.get("CLOUDMR_EMAIL")
                 or prompt("CloudMR email", cfg.get("email")))
        password = (args.password or os.environ.get("CLOUDMR_PASSWORD")
                    or prompt("CloudMR password", secret=True))
    api_key = args.api_key or cfg.get("api_key") or f"camrie-{uuid.uuid4().hex[:24]}"

    # Login to Brain first, so bad credentials fail before anything is created
    print(f"\n{color('[1/5]', 'bold')} Logging in to CloudMR Brain...")
    if register:
        auth = brain_login(email, password)
        token = auth.get("id_token") or auth.get("idToken")
        user_id = auth.get("user_id", "unknown")
        print(color(f"  Logged in as {email} (user: {user_id})", "green"))
    else:
        print(color("  Skipped (--no-register): stack only, no Brain registration", "yellow"))

    # Check AWS credentials
    print(f"\n{color('[2/5]', 'bold')} Checking AWS credentials...")
    session = get_session(profile, region)
    sts = session.client("sts")
    identity = sts.get_caller_identity()
    account_id = identity["Account"]
    print(color(f"  AWS Account: {account_id} ({profile})", "green"))

    # Detect networking
    print(f"\n{color('[3/5]', 'bold')} Detecting VPC and subnets...")
    ec2 = session.client("ec2")
    vpcs = ec2.describe_vpcs(Filters=[{"Name": "is-default", "Values": ["true"]}])["Vpcs"]
    if not vpcs:
        vpcs = ec2.describe_vpcs()["Vpcs"]
    vpc_id = vpcs[0]["VpcId"]

    subnets = ec2.describe_subnets(
        Filters=[{"Name": "vpc-id", "Values": [vpc_id]},
                 {"Name": "map-public-ip-on-launch", "Values": ["true"]}]
    )["Subnets"]
    if len(subnets) < 2:
        subnets = ec2.describe_subnets(
            Filters=[{"Name": "vpc-id", "Values": [vpc_id]}])["Subnets"]

    subnet1 = subnets[0]["SubnetId"]
    subnet2 = subnets[1]["SubnetId"] if len(subnets) > 1 else subnet1
    print(color(f"  VPC: {vpc_id}", "green"))
    print(color(f"  Subnets: {subnet1}, {subnet2}", "green"))

    # Deploy stack
    print(f"\n{color('[4/5]', 'bold')} Deploying CloudFormation stack...")
    print(f"  Stack: {STACK_NAME}")
    print(f"  This takes 2-3 minutes...\n")

    cf = session.client("cloudformation")
    with open(TEMPLATE_PATH) as f:
        template_body = f.read()

    params = [
        {"ParameterKey": "VpcId", "ParameterValue": vpc_id},
        {"ParameterKey": "SubnetId1", "ParameterValue": subnet1},
        {"ParameterKey": "SubnetId2", "ParameterValue": subnet2},
        {"ParameterKey": "WorkerApiKey", "ParameterValue": api_key},
        {"ParameterKey": "WorkerImageUri", "ParameterValue": ECR_IMAGE},
    ]
    caps = ["CAPABILITY_IAM", "CAPABILITY_AUTO_EXPAND"]

    existing, _ = get_stack_outputs(session)
    if existing in ("ROLLBACK_COMPLETE", "ROLLBACK_FAILED", "DELETE_FAILED"):
        # A stack in these states cannot be updated; it must be removed first.
        print(color(f"  Previous stack is {existing}; deleting it first...", "yellow"))
        empty_stack_buckets(session)
        cf.delete_stack(StackName=STACK_NAME)
        cf.get_waiter("stack_delete_complete").wait(
            StackName=STACK_NAME, WaiterConfig={"Delay": 10, "MaxAttempts": 60})
        existing = None

    wait_for = None
    if existing is None:
        cf.create_stack(StackName=STACK_NAME, TemplateBody=template_body,
                        Parameters=params, Capabilities=caps)
        wait_for = "stack_create_complete"
    else:
        try:
            cf.update_stack(StackName=STACK_NAME, TemplateBody=template_body,
                            Parameters=params, Capabilities=caps)
            wait_for = "stack_update_complete"
        except cf.exceptions.ClientError as e:
            if "No updates are to be performed" not in str(e):
                raise
            print(color("  Stack already up to date.", "green"))

    if wait_for:
        try:
            cf.get_waiter(wait_for).wait(
                StackName=STACK_NAME, WaiterConfig={"Delay": 10, "MaxAttempts": 60})
        except Exception as e:
            print(color(f"  Deploy failed: {e}", "red"))
            print_stack_failures(cf)
            sys.exit(1)

    status, outputs = get_stack_outputs(session)
    endpoint = outputs.get("WorkerEndpoint", "")
    print(color(f"  Stack deployed: {status}", "green"))
    print(color(f"  Endpoint: {endpoint}", "green"))

    if not register:
        print(color("\n  Stack is up. Brain registration skipped (--no-register).", "yellow"))
        save_config(profile=profile, region=region, endpoint=endpoint, api_key=api_key)
        return

    # Register with Brain
    print(f"\n{color('[5/5]', 'bold')} Registering with CloudMR Brain...")
    alias = args.alias or f"CAMRIE Worker ({profile})"
    payload = {
        "appName": APP_NAME,
        "mode": "mode_2",
        "provider": "self-hosted",
        "apiEndpoint": endpoint,
        "apiKey": api_key,
        "alias": alias,
        "awsAccountId": account_id,
        "region": region,
        "resultsBucket": "cloudmr-results-cloudmrhub-brain-us-east-1",
        "failedBucket": "cloudmr-failed-cloudmrhub-brain-us-east-1",
        "dataBucket": "cloudmr-data-cloudmrhub-brain-us-east-1",
    }
    resp = requests.post(
        f"{BRAIN_API_URL}/api/computing-unit/register",
        headers={"Authorization": f"Bearer {token}"},
        json=payload,
        timeout=60,
    )
    try:
        reg = resp.json()
    except ValueError:
        reg = {}
    cu_id = reg.get("computingUnitId")
    if resp.status_code >= 300 or not cu_id:
        # The stack is up; only registration failed. Say so rather than
        # printing a fake success - the web GUI won't list this worker.
        print(color(f"  Registration FAILED (HTTP {resp.status_code}): "
                    f"{str(reg or resp.text)[:300]}", "red"))
        print("  The stack is deployed. Re-run deploy to retry registration.")
        save_config(profile=profile, region=region, email=email,
                    alias=alias, endpoint=endpoint, api_key=api_key)
        sys.exit(1)
    print(color(f"  Registered: {alias} (ID: {cu_id})", "green"))

    print(color("\n  Done! Your CAMRIE Mode 2 worker is ready.", "green"))
    print(f"  Submit simulation jobs from the web app selecting your worker.")
    print(f"  Run 'python worker/manage.py status' to check health.")
    print(f"  Run 'python worker/manage.py teardown' to stop all costs.\n")

    save_config(profile=profile, region=region, email=email,
                alias=alias, endpoint=endpoint, api_key=api_key)


def cmd_status(args):
    """Check worker health and running tasks."""
    print(color("\n  CAMRIE Worker Status\n", "bold"))

    cfg = load_config()
    profile = args.profile or cfg.get("profile", "default")
    region = args.region or cfg.get("region", DEFAULT_REGION)
    session = get_session(profile, region)

    status, outputs = get_stack_outputs(session)
    if not status:
        print(color("  Stack not found. Run 'deploy' first.", "red"))
        return

    print(f"  Stack:    {STACK_NAME}")
    print(f"  Status:   {color(status, 'green' if 'COMPLETE' in status else 'yellow')}")

    endpoint = outputs.get("WorkerEndpoint", "")
    if endpoint:
        print(f"  Endpoint: {endpoint}")
        try:
            resp = requests.get(f"{endpoint}/health", timeout=10)
            health = resp.json()
            print(f"  Health:   {color('OK', 'green')}")
            print(f"  Type:     {health.get('type', 'unknown')}")
            print(f"  App:      {health.get('application', 'CAMRIE')}")
        except Exception as e:
            print(f"  Health:   {color(f'UNREACHABLE ({e})', 'red')}")

    cluster = outputs.get("ClusterName") or f"{STACK_NAME}-cluster"
    ecs = session.client("ecs")
    try:
        tasks = ecs.list_tasks(cluster=cluster)["taskArns"]
        print(f"\n  Running tasks: {len(tasks)}")
        for arn in tasks:
            detail = ecs.describe_tasks(cluster=cluster, tasks=[arn])["tasks"][0]
            started = detail.get("startedAt", "")
            lst = detail.get("lastStatus", "?")
            print(f"    {lst} — started {started}")
    except Exception:
        print(f"  Running tasks: 0")
    print()


def cmd_logs(args):
    """Tail recent computation logs."""
    cfg = load_config()
    profile = args.profile or cfg.get("profile", "default")
    region = args.region or cfg.get("region", DEFAULT_REGION)
    session = get_session(profile, region)

    log_group = f"/ecs/{STACK_NAME}"
    logs_client = session.client("logs")

    print(color(f"\n  Tailing logs: {log_group}\n", "bold"))
    print("  (Press Ctrl+C to stop)\n")

    start_time = int((datetime.utcnow() - timedelta(minutes=args.minutes)).timestamp() * 1000)
    seen = set()

    try:
        while True:
            try:
                resp = logs_client.filter_log_events(
                    logGroupName=log_group, startTime=start_time,
                    interleaved=True, limit=50)
            except logs_client.exceptions.ResourceNotFoundException:
                print(color("  No logs yet (no tasks have run).", "yellow"))
                break

            for event in resp.get("events", []):
                eid = event["eventId"]
                if eid in seen:
                    continue
                seen.add(eid)
                ts = datetime.fromtimestamp(event["timestamp"] / 1000).strftime("%H:%M:%S")
                msg = event["message"].strip()
                print(f"  [{ts}] {msg}")
                start_time = event["timestamp"] + 1

            if not args.follow:
                break
            time.sleep(2)
    except KeyboardInterrupt:
        print("\n  Stopped.")


def cmd_costs(args):
    """Show estimated costs from recent tasks."""
    cfg = load_config()
    profile = args.profile or cfg.get("profile", "default")
    region = args.region or cfg.get("region", DEFAULT_REGION)
    session = get_session(profile, region)

    print(color("\n  CAMRIE Cost Estimate (last 30 days)\n", "bold"))

    # Fargate pricing: $0.04048/vCPU/hr + $0.004445/GB/hr
    # CAMRIE config: 4 vCPU, 16 GB
    cost_per_sec = (0.04048 * 4 + 0.004445 * 16) / 3600

    cluster = f"{STACK_NAME}-cluster"
    ecs = session.client("ecs")

    try:
        stopped = ecs.list_tasks(cluster=cluster, desiredStatus="STOPPED")["taskArns"]
        total_seconds = 0

        if stopped:
            details = ecs.describe_tasks(cluster=cluster, tasks=stopped[:100])["tasks"]
            for t in details:
                started = t.get("startedAt")
                stopped_at = t.get("stoppedAt")
                if started and stopped_at:
                    total_seconds += (stopped_at - started).total_seconds()

        running = ecs.list_tasks(cluster=cluster, desiredStatus="RUNNING")["taskArns"]
        total_cost = total_seconds * cost_per_sec

        print(f"  Tasks completed:  {len(stopped)}")
        print(f"  Tasks running:    {len(running)}")
        print(f"  Total compute:    {total_seconds/60:.1f} minutes")
        print(f"  Estimated cost:   ${total_cost:.4f}")
        print(f"  (4 vCPU / 16 GB @ ${cost_per_sec*3600:.4f}/hr)")
        print(f"\n  Idle cost:        {color('$0.00', 'green')}")
        print()
    except Exception as e:
        print(f"  Could not retrieve task history: {e}")
        print(f"  Idle cost is $0.00 (no always-on resources).\n")


def cmd_teardown(args):
    """Delete the stack and deregister from Brain."""
    cfg = load_config()
    profile = args.profile or cfg.get("profile", "default")
    region = args.region or cfg.get("region", DEFAULT_REGION)
    session = get_session(profile, region)

    status, outputs = get_stack_outputs(session)
    if not status:
        print(color("  Stack not found. Nothing to tear down.", "yellow"))
        return

    print(color("\n  Teardown CAMRIE Mode 2 Worker\n", "bold"))
    print(f"  Stack:  {STACK_NAME}")
    print(f"  Status: {status}\n")

    if not args.yes:
        confirm = input(color("  Delete all resources? [y/N]: ", "yellow"))
        if confirm.lower() != "y":
            print("  Cancelled.")
            return

    # Deregister from Brain
    print("  Deregistering from CloudMR Brain...")
    email = args.email or os.environ.get("CLOUDMR_EMAIL") or cfg.get("email")
    password = args.password or os.environ.get("CLOUDMR_PASSWORD")
    if email and not password:
        password = prompt("CloudMR password (to deregister)", secret=True)

    if email and password:
        try:
            auth = brain_login(email, password)
            token = auth.get("id_token") or auth.get("idToken")
            endpoint = cfg.get("endpoint") or outputs.get("WorkerEndpoint", "")

            resp = requests.get(
                f"{BRAIN_API_URL}/api/computing-unit/list",
                headers={"Authorization": f"Bearer {token}"},
                params={"app_name": APP_NAME})
            units = resp.json().get("computingUnits", [])
            our_unit = next((u for u in units if u.get("apiEndpoint") == endpoint), None)

            if our_unit:
                cu_id = our_unit["computingUnitId"]
                requests.post(
                    f"{BRAIN_API_URL}/api/computing-unit/delete",
                    headers={"Authorization": f"Bearer {token}"},
                    json={"computingUnitId": cu_id})
                print(color(f"  Deregistered: {our_unit.get('alias')} ({cu_id})", "green"))
            else:
                print(color("  No matching unit found (already removed?).", "yellow"))
        except Exception as e:
            print(color(f"  Warning: deregister failed: {e}", "yellow"))
    else:
        print(color("  Skipping deregistration (no credentials).", "yellow"))

    # Delete stack (buckets must be empty or the delete fails)
    empty_stack_buckets(session)
    print("  Deleting CloudFormation stack...")
    cf = session.client("cloudformation")
    cf.delete_stack(StackName=STACK_NAME)
    waiter = cf.get_waiter("stack_delete_complete")
    waiter.wait(StackName=STACK_NAME, WaiterConfig={"Delay": 10, "MaxAttempts": 30})
    print(color("  Stack deleted. All costs stopped.", "green"))

    if CONFIG_PATH.exists():
        CONFIG_PATH.unlink()
        print(f"  Config removed: {CONFIG_PATH}")
    print()


# ═══════════════════════════════════════════════════════════════
# GUI Mode (tkinter)
# ═══════════════════════════════════════════════════════════════
def run_gui():
    """Tkinter GUI for managing the CAMRIE Mode 2 worker."""
    try:
        import tkinter as tk
        from tkinter import ttk, scrolledtext
    except ImportError:
        print("tkinter not available. Use CLI mode or install python3-tk.")
        sys.exit(1)

    import threading
    import io
    import re

    root = tk.Tk()
    root.title("CAMRIE — Mode 2 Worker Manager")
    root.geometry("780x680")
    root.resizable(True, True)

    cfg = load_config()
    var_profile = tk.StringVar(value=cfg.get("profile", os.environ.get("AWS_PROFILE", "default")))
    var_region = tk.StringVar(value=cfg.get("region", DEFAULT_REGION))
    var_email = tk.StringVar(value=cfg.get("email", os.environ.get("CLOUDMR_EMAIL", "")))
    var_password = tk.StringVar(value=os.environ.get("CLOUDMR_PASSWORD", ""))
    var_alias = tk.StringVar(value=cfg.get("alias", "My CAMRIE Worker"))

    # ═══════════════════════════════════════════════════════════
    # Notebook (Tabs)
    # ═══════════════════════════════════════════════════════════
    notebook = ttk.Notebook(root)
    notebook.pack(fill="both", expand=True, padx=5, pady=5)

    # ═══════════════════════════════════════════════════════════
    # TAB 1: Worker Management
    # ═══════════════════════════════════════════════════════════
    worker_tab = ttk.Frame(notebook)
    notebook.add(worker_tab, text="  Worker  ")

    settings_frame = ttk.LabelFrame(worker_tab, text="Settings", padding=10)
    settings_frame.pack(fill="x", padx=10, pady=5)

    row = 0
    ttk.Label(settings_frame, text="AWS Profile:").grid(row=row, column=0, sticky="w", pady=2)
    profiles = get_aws_profiles()
    ttk.Combobox(settings_frame, textvariable=var_profile, values=profiles, width=43
                 ).grid(row=row, column=1, sticky="ew", pady=2, padx=(5, 0))
    row += 1

    for label, var, show in [
        ("AWS Region:", var_region, None),
        ("CloudMR Email:", var_email, None),
        ("CloudMR Password:", var_password, "*"),
        ("Worker Alias:", var_alias, None),
    ]:
        ttk.Label(settings_frame, text=label).grid(row=row, column=0, sticky="w", pady=2)
        entry = ttk.Entry(settings_frame, textvariable=var, width=45)
        if show:
            entry.config(show=show)
        entry.grid(row=row, column=1, sticky="ew", pady=2, padx=(5, 0))
        row += 1

    settings_frame.columnconfigure(1, weight=1)

    # Buttons
    btn_frame = ttk.Frame(worker_tab, padding=5)
    btn_frame.pack(fill="x", padx=10)

    # Log output
    log_frame = ttk.LabelFrame(worker_tab, text="Output", padding=5)
    log_frame.pack(fill="both", expand=True, padx=10, pady=5)

    log_widget = scrolledtext.ScrolledText(log_frame, height=14, font=("Courier", 10), state="disabled")
    log_widget.pack(fill="both", expand=True)

    def clear_log():
        log_widget.config(state="normal")
        log_widget.delete("1.0", "end")
        log_widget.config(state="disabled")

    def append_log(text):
        log_widget.config(state="normal")
        log_widget.insert("end", text + "\n")
        log_widget.see("end")
        log_widget.config(state="disabled")

    def make_args():
        ns = argparse.Namespace()
        ns.profile = var_profile.get() or None
        ns.region = var_region.get() or None
        ns.email = var_email.get() or None
        ns.password = var_password.get() or None
        ns.api_key = None
        ns.alias = var_alias.get() or None
        ns.yes = True
        ns.follow = False
        ns.minutes = 60
        return ns

    def run_cmd(fn):
        clear_log()

        def wrapper():
            old_stdout = sys.stdout
            sys.stdout = buffer = io.StringIO()
            try:
                fn(make_args())
            except SystemExit:
                pass
            except Exception as e:
                print(f"\nError: {e}")
            finally:
                sys.stdout = old_stdout
                output = buffer.getvalue()
                clean = re.sub(r'\033\[[0-9;]*m', '', output)
                root.after(0, lambda: append_log(clean))

        threading.Thread(target=wrapper, daemon=True).start()

    ttk.Button(btn_frame, text="Deploy", command=lambda: run_cmd(cmd_deploy)).pack(side="left", padx=3)
    ttk.Button(btn_frame, text="Status", command=lambda: run_cmd(cmd_status)).pack(side="left", padx=3)
    ttk.Button(btn_frame, text="Logs", command=lambda: run_cmd(cmd_logs)).pack(side="left", padx=3)
    ttk.Button(btn_frame, text="Costs", command=lambda: run_cmd(cmd_costs)).pack(side="left", padx=3)
    ttk.Button(btn_frame, text="Teardown", command=lambda: run_cmd(cmd_teardown)).pack(side="left", padx=3)
    ttk.Button(btn_frame, text="Clear", command=clear_log).pack(side="right", padx=3)

    # ═══════════════════════════════════════════════════════════
    # TAB 2: Debug Pipelines
    # ═══════════════════════════════════════════════════════════
    debug_tab = ttk.Frame(notebook)
    notebook.add(debug_tab, text="  Debug Pipelines  ")

    lookup_frame = ttk.LabelFrame(debug_tab, text="Pipeline Lookup", padding=10)
    lookup_frame.pack(fill="x", padx=10, pady=5)

    var_pipeline_id = tk.StringVar()
    ttk.Label(lookup_frame, text="Pipeline ID:").grid(row=0, column=0, sticky="w", pady=2)
    ttk.Entry(lookup_frame, textvariable=var_pipeline_id, width=45
              ).grid(row=0, column=1, sticky="ew", pady=2, padx=(5, 0))
    lookup_frame.columnconfigure(1, weight=1)

    debug_btn_frame = ttk.Frame(debug_tab, padding=5)
    debug_btn_frame.pack(fill="x", padx=10)

    debug_log_frame = ttk.LabelFrame(debug_tab, text="Pipeline Info", padding=5)
    debug_log_frame.pack(fill="both", expand=True, padx=10, pady=5)

    debug_log = scrolledtext.ScrolledText(debug_log_frame, height=15, font=("Courier", 10), state="disabled")
    debug_log.pack(fill="both", expand=True)

    def clear_debug():
        debug_log.config(state="normal")
        debug_log.delete("1.0", "end")
        debug_log.config(state="disabled")

    def append_debug(text):
        debug_log.config(state="normal")
        debug_log.insert("end", text + "\n")
        debug_log.see("end")
        debug_log.config(state="disabled")

    def debug_list_pipelines():
        clear_debug()
        email = var_email.get()
        password = var_password.get()

        def worker():
            try:
                if not email or not password:
                    print("Enter CloudMR email and password in the Worker tab.")
                    return
                auth = brain_login(email, password)
                token = auth.get("id_token") or auth.get("idToken")
                headers = {"Authorization": f"Bearer {token}"}

                print("Fetching CAMRIE pipelines...\n")
                resp = requests.get(f"{BRAIN_API_URL}/api/pipeline/list",
                                    headers=headers, params={"app_name": APP_NAME})
                data = resp.json()
                pipelines = data if isinstance(data, list) else data.get("pipelines", [])

                if not pipelines:
                    print("No pipelines found.")
                    return

                pipelines.sort(key=lambda p: p.get("created_at", p.get("createdAt", "")), reverse=True)

                print(f"{'Status':<12} {'Alias':<30} {'Pipeline ID':<38} {'Date'}")
                print(f"{'─'*12} {'─'*30} {'─'*38} {'─'*20}")
                for p in pipelines[:50]:
                    status = p.get("status", "?")
                    alias = (p.get("alias", "") or "")[:28]
                    pid = p.get("pipeline") or p.get("pipelineId") or p.get("id", "")
                    date = (p.get("created_at") or p.get("createdAt") or "")[:19]
                    marker = "!" if "fail" in status.lower() else " "
                    print(f"{marker}{status:<11} {alias:<30} {pid:<38} {date}")

                statuses = {}
                for p in pipelines:
                    s = p.get("status", "unknown")
                    statuses[s] = statuses.get(s, 0) + 1
                print(f"\n  Total: {len(pipelines)} | Status: {statuses}")

            except Exception as e:
                print(f"Error: {e}")

        def run():
            old_stdout = sys.stdout
            sys.stdout = buffer = io.StringIO()
            try:
                worker()
            finally:
                sys.stdout = old_stdout
                output = buffer.getvalue()
                clean = re.sub(r'\033\[[0-9;]*m', '', output)
                root.after(0, lambda: append_debug(clean))

        threading.Thread(target=run, daemon=True).start()

    def debug_lookup_pipeline():
        clear_debug()
        pipeline_id = var_pipeline_id.get().strip()
        email = var_email.get()
        password = var_password.get()

        if not pipeline_id:
            append_debug("Enter a pipeline ID first.")
            return

        def worker():
            try:
                if not email or not password:
                    print("Enter CloudMR credentials in the Worker tab.")
                    return
                auth = brain_login(email, password)
                token = auth.get("id_token") or auth.get("idToken")
                headers = {"Authorization": f"Bearer {token}"}

                print(f"Looking up pipeline: {pipeline_id}\n")
                resp = requests.get(f"{BRAIN_API_URL}/api/pipeline/{pipeline_id}", headers=headers)

                if resp.status_code != 200:
                    print(f"Pipeline not found (HTTP {resp.status_code})")
                    return

                data = resp.json()
                if isinstance(data, list):
                    data = data[0] if data else {}

                print(f"{'═'*60}")
                print(f"  Pipeline Details")
                print(f"{'═'*60}")
                print(f"  ID:      {pipeline_id}")
                print(f"  Status:  {data.get('status', 'unknown')}")
                print(f"  Alias:   {data.get('alias', 'N/A')}")
                print(f"  User:    {data.get('user_id', data.get('userId', 'N/A'))}")
                print(f"  Created: {data.get('created_at', data.get('createdAt', 'N/A'))}")

                # Show task details if available
                task = data.get("task", {})
                if task:
                    print(f"\n  Task:")
                    print(f"    Name: {task.get('name', '?')}")
                    print(f"    Type: {task.get('type', '?')}")
                    files = task.get("files", [])
                    print(f"    Files: {files}")
                    opts = task.get("options", {})
                    seqs = opts.get("sequences") or ([opts["sequence"]] if opts.get("sequence") else [])
                    if seqs:
                        print(f"    Sequences: {len(seqs)}")

                output = data.get("output") or data.get("results")
                if output:
                    print(f"\n  Output: {output}")

                    # Try to read the result/failure zip
                    if output.startswith("s3://"):
                        profile = var_profile.get() or "default"
                        try:
                            import tempfile, zipfile
                            parts = output.replace("s3://", "").split("/", 1)
                            bucket, key = parts[0], parts[1]
                            session = get_session(profile)
                            s3 = session.client("s3")
                            tmp = tempfile.NamedTemporaryFile(suffix=".zip", delete=False)
                            s3.download_file(bucket, key, tmp.name)
                            with zipfile.ZipFile(tmp.name, "r") as zf:
                                names = zf.namelist()
                                print(f"\n  Files in zip: {names}")
                                if "error.txt" in names:
                                    with zf.open("error.txt") as f:
                                        err = f.read().decode("utf-8", errors="replace")
                                    print(f"\n  Error:\n  {err.strip()[:500]}")
                            os.unlink(tmp.name)
                        except Exception as e:
                            print(f"\n  Could not read zip: {e}")

                print(f"\n{'═'*60}")

            except Exception as e:
                print(f"Error: {e}")

        def run():
            old_stdout = sys.stdout
            sys.stdout = buffer = io.StringIO()
            try:
                worker()
            finally:
                sys.stdout = old_stdout
                output = buffer.getvalue()
                clean = re.sub(r'\033\[[0-9;]*m', '', output)
                root.after(0, lambda: append_debug(clean))

        threading.Thread(target=run, daemon=True).start()

    ttk.Button(debug_btn_frame, text="List Pipelines", command=debug_list_pipelines).pack(side="left", padx=3)
    ttk.Button(debug_btn_frame, text="Lookup Pipeline", command=debug_lookup_pipeline).pack(side="left", padx=3)
    ttk.Button(debug_btn_frame, text="Clear", command=clear_debug).pack(side="right", padx=3)

    root.mainloop()


# ═══════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════
def main():
    parser = argparse.ArgumentParser(
        description="CAMRIE Mode 2 — Worker Manager",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Commands:
  deploy    Deploy worker to your AWS account
  status    Check health and running tasks
  logs      View computation logs
  costs     Show cost estimates
  teardown  Delete everything (stop all costs)

GUI mode (default):
  python worker/manage.py        Opens graphical interface
  python worker/manage.py --gui  Same as above
        """)
    parser.add_argument("command", nargs="?",
                        choices=["deploy", "status", "logs", "costs", "teardown"])
    parser.add_argument("--gui", "-g", action="store_true", help="Open GUI")
    parser.add_argument("--profile", "-p", help="AWS CLI profile")
    parser.add_argument("--region", "-r", help="AWS region")
    parser.add_argument("--email", "-e", help="CloudMR email")
    parser.add_argument("--password", help="CloudMR password")
    parser.add_argument("--api-key", help="Worker API key")
    parser.add_argument("--alias", help="Worker alias")
    parser.add_argument("--yes", "-y", action="store_true", help="Skip confirmations")
    parser.add_argument("--follow", "-f", action="store_true", help="Follow logs")
    parser.add_argument("--minutes", "-m", type=int, default=30, help="Minutes of logs")
    parser.add_argument("--no-register", action="store_true",
                        help="deploy: create the stack only, skip CloudMR Brain registration")

    args = parser.parse_args()

    if args.gui or (not args.command):
        run_gui()
        return

    commands = {
        "deploy": cmd_deploy,
        "status": cmd_status,
        "logs": cmd_logs,
        "costs": cmd_costs,
        "teardown": cmd_teardown,
    }
    commands[args.command](args)


if __name__ == "__main__":
    main()
